### ISSUE TITLE
Проблема с передачей аватара на ICMS 2.2.1

### ISSUE THREAD

**Issue by nomad48** [ulogin/ulogin-InstantCMS#1]
Добрый день, Уважаемые разработчики uLogin!
Установил Ваш компонент на свой сайт под InstantCMS 2.2.1, есть проблема.
Неправильно передаётся аватар при авторизации. У меня в виджете в возвращаемых полях профиля установлена "большая аватарка" -  из всех соцсетей правильно только передаёт авторизация через mail.ru, так как у меня задумано на главной 100х100 пикселей и 230х260 в профиле пользователя.
Остальные соц сети почему-то уменьшаются аватары до 64х64 на главной и в профилях пользователя вообще логики нет и 200х200, и 200х125, и 200х205 в зависимости от соцсети. Подскажите какие параметры изменить и где копать чтобы поправить данную проблему.
В приложениях скриншот проблемы. Дистрибутив вашего компонента качал здесь, на github.
Мой сайт http://lovelovely.ru
Заранее спасибо за помощь.
С ув. Андрей!
![21-07-2015 12-58-46](https://cloud.githubusercontent.com/assets/9349934/8804569/828bbe06-2fd5-11e5-98ec-847c3c9bb10a.png)

**Comment by ulogin-team** [comment]
Здравствуйте. 
А в админке у вас какие настройки в разделе "пользователи"->"настройки профилей"->"аватары"? 
По-умолчанию, насколько я вижу, выставлены такие - https://goo.gl/H2e77L. 
Я посмотрел код плагина, там используется, как положено, большая аватара (если она отдается соцсетью). Далее плагин уменьшает изображение согласно настройкам в админке и сохраняет два изображения - маленькое и большое. Маленькое, с настройками по-умолчанию, получается 64х64. Попробуйте поднять до 100 и посмотрите результат. 
Для меня остался только немного неясным момент с аватаркой 130х130 и откуда она взялась. Она такая одна или через mail.ru все такие? 

P.S. удалите, пожалуйста, мои свежесозданные профили APAKC и IVAN.

**Comment by nomad48** [comment]
Добрый день, в админке для второй версии аватары так настраиваются. http://joxi.ru/j1A5qdkU486xAE  то есть большое 230х260 для профиля, маленькое 130х130 для разных мест сайта (комментарии, галерея пользователей, знакомства, встречи и т.д.) и микро 32х32 для различных виджетов.
В компонентах Галерея пользователей, знакомствах и встречах картинка в CSS и так прописана 100х100 пикселей http://joxi.ru/752aGbDUlwQdr0, а передается она туда от 130х130 пикселей (писал выше), уменьшая ее.
В данном случае я не пойму откуда берется изображение 64х64 пикселя в Галерее пользователей, это так передает его uLogin? http://joxi.ru/BLmGYJofBOjwAl и как мне сделать чтобы uLogin генерировал не 64х64 пикселя, а 130х130 для разных мест сайта.
Странно, но как я вам написал в топике, только авторизация через mail.ru, через uLogin отдаёт правильно все аватары по моим настройкам, большой 230х260, маленький аватар 130х130, и микро 32х32, а остальные соц сети как я и писал как им хочется, каких размеров только нет:))) Вот как это исправить.
Профили удалил.

**Comment by nomad48** [comment]
Когда вручную загружаешь и меняешь у юзера аватар из соцсети, то все отображается нормально.

**Comment by ulogin-team** [comment]
Нашли и исправили проблему.
Установите, пожалуйста, новую версию (можно просто заменить файл https://github.com/ulogin/ulogin-InstantCMS/blob/d2e181af195b3a2d30bd286347aec38ae92e273d/package/system/controllers/ulogin/actions/login.php) и проверьте работу теперь.

**Comment by nomad48** [comment]
Попробовал на одной социальной сети (Google+), работает. Спасибо за компонент и исправление багов!

**Comment by ulogin-team** [comment]
Отлично!
Пишите, если возникнут проблемы, рады помочь.
