### ISSUE TITLE
Проблема с авторизацией через Твиттер

### ISSUE THREAD

**Issue by nomad48** [ulogin/ulogin-InstantCMS#10]
Добрый день, перестал работать Твиттер в uLogin, при попытке авторизации, такое окно выдаёт.
![01-04-2018 01-22-18](https://user-images.githubusercontent.com/9349934/38170362-9d4f7cfe-358c-11e8-8069-5f48255ae1dd.png)

**Comment by ulogin-team** [comment]
Да, авторизация через твиттер не работает. Скорее всего, уже не заработает. 
Мы рекомендуем вам отключить ее на своем сайте. Через некоторое время мы уберем твиттер из списка доступных сервисов.
