### ISSUE TITLE
Проблема с аватарами

### ISSUE THREAD

**Issue by nomad48** [ulogin/ulogin-InstantCMS#11]
Добрый день уважаемые разработчики. В uLogin появилась проблема с аватарами.
При создании пресета аватара с размером микро, он его не делает квадратным, а оставляет пропорционально размерам реального аватара загруженного из соцсети. Хотя в настройках загрузки изображений указано 32х32 делать квадратным
![18-08-2018 11-57-35](https://user-images.githubusercontent.com/9349934/44297696-98839600-a2de-11e8-9c3f-c02e46643c0c.png)
![18-08-2018 12-03-48](https://user-images.githubusercontent.com/9349934/44297728-04fe9500-a2df-11e8-9897-f684c5d50615.png)
Помогите пожалуйста поправить.
Версия ICMS 2.10.1

**Comment by nomad48** [comment]
Версия 2.12.0 ICMS всё также. Парни, вы забросили проект?

**Comment by ulogin-team** [comment]
Проблему исправили, обновление выпустили. 
Спасибо, что напомнили )
