### ISSUE TITLE
Не устанавливается на 2.4.0

### ISSUE THREAD

**Issue by vlad7090** [ulogin/ulogin-InstantCMS#3]
Во время установки выдает ошибку install_package_info.tpl.php on line 102

 Undefined index: info in /templates/default/controllers/admin/install_package_info.tpl.php on line 19 v Notice: Undefined index: version in /templates/default/controllers/admin/install_package_info.tpl.php on line 21 . Notice: Undefined index: version in

**Comment by ulogin-team** [comment]
Вы пытались установить версию для InstantCMS 1.\* 
Используйте версию для InstantCMS 2.*: https://github.com/ulogin/ulogin-InstantCMS/tree/instantcms2
