### ISSUE TITLE
Ошибки и нотисы при обновлении до 2.4.0

### ISSUE THREAD

**Issue by nomad48** [ulogin/ulogin-InstantCMS#4]
Добрый день, обновил движок до  версии 2.4.0, в логах появились следующие ошибки и нотисы:

Подскажите пожалуйста как убрать. Спасибо.

**Comment by maxisoft-git** [comment]
у меня на 2.4 вообще не заработало ничего. ошибок нет но и регистрация не происходит.

**Comment by nomad48** [comment]
Есть решение уже, почему Вы не добавляете его в дистрибутив?

```
//--------------------
    public function getUloginUserNetworks ($user_id = 0) {
        $this->resetFilters();
        $this->filterEqual('user_id', $user_id);
        $q = $this->get('ulogin_user');
        if (is_array($q)) {
            foreach ($q as $q0) {
                $result[] = $q0['network'];
            }
        }
        return $result;
    }

```

**Comment by ulogin-team** [comment]
Данная ошибка никак не связана с версией 2.4, видимо, у вас просто совпадение. 
В любом случае, эту и несколько других обнаруженных ошибок исправили в новой версии, которую только что опубликовали. 

Спасибо, что обратили наше внимание!
