### ISSUE TITLE
Сломана верстка на Вашем сайте

### ISSUE THREAD

**Issue by nomad48** [ulogin/ulogin-InstantCMS#5]
Добрый день, на Вашем основном сайте сломана верстка в личном кабинете при настройке виджета, из-за этого не понятно как и что настраивать, в виджете появляются не нужные пункты. Исправьте пожалуйста.
![10-09-2016 12-51-40](https://cloud.githubusercontent.com/assets/9349934/18409669/f57462d8-7755-11e6-9ee2-ac0ab7bf520c.png)

**Comment by ipshenicyn** [comment]
Честно говоря, пока без понятия, как у вас могла сложиться такая проблема. Ничего подобного не наблюдали сами и нам ни разу не сообщали о подобных проблемах. 
Прямо сейчас в хроме и FF в ЛК все отлично. Какой у вас браузер? В режиме инкогнито попробуйте, пожалуйста.

**Comment by nomad48** [comment]
Да сейчас всё нормально, я сам не знаю почему так было. Поэтому написал Вам.

**Comment by nomad48** [comment]
Закройте коммит пожалуйста!
