### ISSUE TITLE
Проблема с пресетами

### ISSUE THREAD

**Issue by nomad48** [ulogin/ulogin-InstantCMS#6]
Добрый вечер, после одного из обновлений, скорее всего 2.0.8 у меня стали возникать проблемы с создаваемыми пресетами пользователей, ранее всё было нормально и такой проблемы я не наблюдал. Суть проблемы, они теряют в качестве. Сейчас пресет small 130х130 который выводится на главную страницу сайта мутный, также мутный маленький пресет micro 32х32. Единственный который создается правильно это пресет normal для аватара в профиле пользователя. Мой сайт [http://lovelovely.ru/](url) пример: пользователь НАТАЛЬЯ ВЕЛИКАНОВА (ФУТИНА).
Помогите пожалуйста решить проблему.

**Comment by ipshenicyn** [comment]
Здравствуйте, Андрей! 

Да, в версиях 2.0.8-2.0.9 мы изменили количество создаваемых изображений из фото пользователя. Вебмастера жаловались, что создается много "мусора". 

Я правильно понял, у вас стандартному пресету small выставлены свои размеры - 130х130? Да, такую ситуацию мы не учли. Исправим сегодня же, простите пожалуйста за неудобства.

**Comment by ipshenicyn** [comment]
Уже выпустили обновление. Попробуйте, пожалуйста, новую версию и расскажите, все ли теперь в порядке.

**Comment by nomad48** [comment]
Спасибо, обновился, вроде всё нормально.
