### ISSUE TITLE
Пустое значение в столбце nickname

### ISSUE THREAD

**Issue by shuma375** [ulogin/ulogin-InstantCMS#7]
Версия instantcms 2.7.1, версия ulogin 2.0.11
После входа через любую из кнопок почты или социальных сетей, в базу не попадают значения nickname. Также не подхватывается и аватар

**Comment by nomad48** [comment]
Что-то наверно обновилось в движке ICMS 2.

**Comment by shuma375** [comment]
Обновлял автоматически, сейчас буду искать в чем дело. У тебя все нормально работает?

**Comment by nomad48** [comment]
Версия uLogin 2.0.11 версия ICMS2 2.6.1 - всё нормально работает, сегодня буду обновляться, проверю. Женя у тебя только при регистрации косяки или и при входе по uLogin?

**Comment by shuma375** [comment]
Да, только при регистрации

**Comment by shuma375** [comment]
Проблема решена
