### ISSUE TITLE
Две проблемы в ICMS 2.7.1

### ISSUE THREAD

**Issue by nomad48** [ulogin/ulogin-InstantCMS#8]
Добрый день. Есть две небольшие проблемы по работе uLogin для второй версии ICMS.

1. При регистрации пользователя через  uLogin, подтягивается аватар, но при редактировании профиля он показывается как пресет micro, хотя в установка стоит пресет normal. Данная проблема была решена [тут](https://github.com/instantsoft/icms2/issues/388), в базе пресеты выставлялись в обратном порядке. Теперь при обычной регистрации все нормально, а при регистрации через uLogin проблема присутствует.

2. При регистрации пользователя через uLogin, не работает запрет регистрации если IP внесён в черный список, Данную проблему я описал [тут](https://github.com/instantsoft/icms2/issues/493) @fuzegit  ответил что при проверке, через обычную регистрацию запрет регистрации если IP внесён в черный список - работает нормально.

**Comment by nomad48** [comment]
обновился до 2.7.2 проблема актуальна

**Comment by nomad48** [comment]
@ulogin-team Скажите пожалуйста, будет решение проблемы?

**Comment by ulogin-team** [comment]
1. Исправили. Но исправили странным костылем, потому что проблема, откровенно говоря, не у нас. Наш плагин при регистрации пользователя получает от системы список пресетов, по списку создает картинки и сохраняет. Если команда движка решила изменить сортировку списка пресетов - почему мы от системы все еще получаем устаревший порядок? Пришлось добавить у себя странную сортировку, хотя это явно костыль. Нам вообще показалось очень странным, что вывод нужной аватары в данном месте происходит исходя из порядка аватар, хранимого в базе. Порядок не должен влиять ни на что в логике системы. 
Как бы то ни было, теперь все должно быть в порядке. Разумеется, не для старых пользователей, у которых порядок уже сохранен в БД. Это еще одна странность логики, которая опирается на порядок хранимый в бд.

2. Добавили нужную проверку. 

Попробуйте новую версию и сообщите, пожалуйста, все ли в порядке.

Спасибо вам за сообщения, в том числе и на почту! К сожалению, иногда нам нужно почувствовать вашу настойчивость, чтобы найти время для исправления старых проблем.

**Comment by nomad48** [comment]
Спасибо, проверю и сообщу о результатах.03.07.2017, 14:52, "uLogin Team" <notifications@github.com>:

Исправили. Но исправили странным костылем, потому что проблема, откровенно говоря, не у нас. Наш плагин при регистрации пользователя получает от системы список пресетов, по списку создает картинки и сохраняет. Если команда движка решила изменить сортировку списка пресетов - почему мы от системы все еще получаем устаревший порядок? Пришлось добавить у себя странную сортировку, хотя это явно костыль. Нам вообще показалось очень странным, что вывод нужной аватары в данном месте происходит исходя из порядка аватар, хранимого в базе. Порядок не должен влиять ни на что в логике системы.
Как бы то ни было, теперь все должно быть в порядке. Разумеется, не для старых пользователей, у которых порядок уже сохранен в БД. Это еще одна странность логики, которая опирается на порядок хранимый в бд.


Добавили нужную проверку.


Попробуйте новую версию и сообщите, пожалуйста, все ли в порядке.
Спасибо вам за сообщения, в том числе и на почту! К сожалению, иногда нам нужно почувствовать вашу настойчивость, чтобы найти время для исправления старых проблем.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- С Уважением Андрей,admin сайта lovelovely.ru

**Comment by nomad48** [comment]
Доброй ночи парни, сейчас у меня ICMS 2.8.2 и проблема с аватарами опять появилась, опять они грузятся в обратном порядке.
То есть проблема та же что и описана в тикете сначала:
При регистрации пользователя через uLogin, подтягивается аватар, но при редактировании профиля он показывается как пресет micro, хотя в установке стоит пресет normal. Теперь при обычной регистрации все нормально, а при регистрации через uLogin проблема опять появилась.
Я связываю это с тем, что в 2.8.0 появилась возможность указывать пресеты для поля аватар - в компоненте профили пользователя (скриншот) 
![05-11-2017 00-03-17](https://user-images.githubusercontent.com/9349934/32409442-d03ec960-c1bc-11e7-92d6-f10cc2e4a804.jpg)
Ссылка на релиз [тут](http://www.instantcms.ru/novosti/release280.html) (скриншот)
![05-11-2017 00-07-34](https://user-images.githubusercontent.com/9349934/32409475-5db283fe-c1bd-11e7-92b7-48bee504d3a7.jpg)

**Comment by nomad48** [comment]
Уважаемые разработчики, исправьте пожалуйста проблемку.

**Comment by ulogin-team** [comment]
Уточните пожалуйста, как мы можем воспроизвести проблему? 
Установили версию 2.8.2. Авторизуемся, идем в редактирование профиля - аватарка не микро https://goo.gl/DHJzDf

**Comment by nomad48** [comment]
Добрый день. Попробуйте выбрать пресеты в настройках компонента Профили пользователей - Поля профиля -  Аватар - Тип поля 
![13-11-2017 11-55-51](https://user-images.githubusercontent.com/9349934/32717152-a82b2ad2-c869-11e7-9bb5-057bd4374fb5.png)

**Comment by ulogin-team** [comment]
В данный момент выбрано вот так (настройки по-умолчанию) https://goo.gl/niy9R3

**Comment by nomad48** [comment]
@ulogin-team да, так

**Comment by ulogin-team** [comment]
Проверьте, пожалуйста, в бд в каком виде у пользователя, у которого наблюдается проблема, сохранились фотки? Например, вот как сохранены у меня: https://goo.gl/TnBgg9 
В прошлый раз. насколько я помню, проблема была именно в порядке, в котором они сохранялись в бд.

**Comment by nomad48** [comment]
@ulogin-team у меня по другому 
![13-11-2017 12-09-31](https://user-images.githubusercontent.com/9349934/32717672-8a7ef61a-c86b-11e7-9acb-23a3733c4347.png)
![13-11-2017 12-09-17](https://user-images.githubusercontent.com/9349934/32717670-87502090-c86b-11e7-8940-5b2b41d5549a.png)

Самое интересное, что эта проблема появилась опять после обновления, когда Вы первый раз исправили все ок было

**Comment by ulogin-team** [comment]
А покажите еще свою таблицу пресетов (cms_images_presets).

**Comment by nomad48** [comment]
@ulogin-team вот
![13-11-2017 12-31-09](https://user-images.githubusercontent.com/9349934/32718561-8aff0140-c86e-11e7-87f6-6f06317ae0d9.png)

**Comment by ulogin-team** [comment]
Есть предположение, с чем связана проблема. 
Наш плагин сортирует пресеты в порядке убывания **на основании поля height**. Насколько я вижу, у вас у пресетов micro, small, normal нет значения в этом поле. В движке по-умолчанию, насколько я вижу у себя, оно есть: https://goo.gl/AbCd3X 

Вы убирали значение высоты осознанно, или оно как-то само так получилось? 

Я вижу два варианта: либо добавить значение height к нужным пресетам, либо в плагине поправить, чтобы он сортировал по полю width. 
Для начала, можете попробовать поправить у себя в коде плагина.
Это файл 
system/controllers/ulogin/actions/login.php
строка 507 
https://goo.gl/KDnMWq

**Comment by nomad48** [comment]
"Вы убирали значение высоты осознанно, или оно как-то само так получилось?" - осознано, потому что юзеры не грузят одинаковые пресеты, все грузят кто, во что горазд, чтобы шаблон не раздвигало, я поставил ширину фиксированную, а высоту авто.
Я поправлю, но это же не универсальное решение, если завтра будет сортировка по высоте.

**Comment by ulogin-team** [comment]
Да, конечно. Это еще не решение. Пока мы только разбираемся, в чем именно проблема. 
Если у вас сработает предложенное мной исправление, то мы доработаем код до более универсального.

**Comment by nomad48** [comment]
Хорошо я поправлю как Вы сказали и при регистрации очередного юзера через ulogin сообщу Вам результаты

**Comment by nomad48** [comment]
Поправил, но у меня это 511 строка, вы  в этот файл добавляли еще проверку по запрещенным для регистрации  IP
![13-11-2017 13-31-49](https://user-images.githubusercontent.com/9349934/32721317-227e9366-c877-11e7-9386-7b8c45268788.png)
когда юзер по uLogin зарегистрируется, я сообщу результаты.

**Comment by ulogin-team** [comment]
Спасибо, будем ждать результатов.

**Comment by nomad48** [comment]
При таких настройках как я сохранил
`return $a['width'] > $b['width'] ? -1 : ($a['width'] < $b['width'] ? 1 : 0);`
при регистрации через uLogin аватар сохраняется нормально
![14-11-2017 21-55-38](https://user-images.githubusercontent.com/9349934/32798702-98247972-c986-11e7-9872-317743159107.jpg)
