### ISSUE TITLE
Адаптация для InstantCMS 2.7.2

### ISSUE THREAD

**Issue by kseniya93** [ulogin/ulogin-InstantCMS#9]
Адаптируйте плагин для InstantCMS 2.7.2, пожалуйста.

**Comment by nomad48** [comment]
Поддерживаю, есть две проблемы, решите пожалуйста.

**Comment by ulogin-team** [comment]
> Адаптируйте плагин для InstantCMS 2.7.2, пожалуйста.

С какими проблемами вы столкнулись, опишите пожалуйста? 
Мы не обнаружили никаких проблем с версией 2.7.2.

**Comment by kseniya93** [comment]
Адаптируйте плагин для InstantCMS 2.8.0, пожалуйста.

**Comment by kseniya93** [comment]
Адаптируйте плагин для InstantCMS 2.8.0 и выложите в каталог, пожалуйста.

**Comment by nomad48** [comment]
Проблемы которые я описывал, ребята поправили. Сейчас нормально всё.
